CREATE TYPE sex AS ENUM ('M', 'F');

CREATE TABLE table_positions
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position TEXT   NOT NULL CHECK (position <> '')
);

CREATE TABLE table_persons
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT   NOT NULL CHECK (first_name <> ''),
    last_name  TEXT   NOT NULL CHECK (last_name <> ''),
    patronymic TEXT   NULL CHECK (patronymic <> ''),
    sex        sex,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE table_emails
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     TEXT   NOT NULL CHECK (email LIKE '%@%'),
    person_id INT    NOT NULL,
    FOREIGN KEY (person_id) REFERENCES table_persons (id)

);

CREATE TABLE table_telephones
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telephone TEXT   NOT NULL,
    person_id INT    NOT NULL,
    FOREIGN KEY (person_id) REFERENCES table_persons (id)
);

CREATE TABLE table_discounts
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount_name TEXT   NOT NULL CHECK (discount_name <> ''),
    discount      INT    NOT NULL CHECK (discount >= 0)
);

CREATE TABLE table_product_types
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                 TEXT   NOT NULL CHECK (type <> ''),
    product_descriptions TEXT   NULL
);

CREATE TABLE table_manufacturers
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manufacturer TEXT   NOT NULL CHECK (manufacturer <> ''),
    address      TEXT   NOT NULL CHECK ( address <> '' ),
    telephone    TEXT   NOT NULL,
    email        TEXT   NOT NULL CHECK (email LIKE '%@%')
);

CREATE TABLE table_order_formats
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    format TEXT   NOT NULL CHECK (format <> '')
);

CREATE TABLE table_metrics
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric TEXT   NOT NULL CHECK (metric <> '')

);

CREATE TABLE table_products
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name       TEXT    NOT NULL CHECK (product_name <> ''),
    product_type_id    INT     NOT NULL,
    price_sale         NUMERIC NOT NULL,
    metric_id          INT     NOT NULL,
    expiration_date    DATE    NULL,
    manufacturing_date DATE    NOT NULL,
    product_quantity   INT     NOT NULL CHECK (product_quantity >= 0),
    prime_cost         NUMERIC NOT NULL CHECK (prime_cost >= 0.0),
    manufacturer_id    INT     NOT NULL,
    product_stock      BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (metric_id) REFERENCES table_metrics (id),
    FOREIGN KEY (manufacturer_id) REFERENCES table_manufacturers (id),
    FOREIGN KEY (product_type_id) REFERENCES table_product_types (id)
);

CREATE TABLE table_price_change_history
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date       DATE    NOT NULL,
    price      NUMERIC NOT NULL CHECK (price >= 0.0),
    product_id INT     NOT NULL,
    FOREIGN KEY (product_id) REFERENCES table_products (id)
);

CREATE TABLE table_product_archive
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT    NOT NULL,
    FOREIGN KEY (product_id) REFERENCES table_products (id)
);

CREATE TABLE table_sellers
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id      INT    NOT NULL,
    positions_id   INT    NOT NULL,
    date_admission DATE   NOT NULL,
    FOREIGN KEY (person_id) REFERENCES table_persons (id),
    FOREIGN KEY (positions_id) REFERENCES table_positions (id)
);

CREATE TABLE table_change_position
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id            INT    NOT NULL,
    previous_position_id INT    NULL,
    new_position_id      INT    NOT NULL,
    FOREIGN KEY (person_id) REFERENCES table_persons (id)
);

CREATE TABLE table_clients
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id    INT    NOT NULL,
    discount_id  INT    NULL,
    subscription BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (person_id) REFERENCES table_persons (id),
    FOREIGN KEY (discount_id) REFERENCES table_discounts (id)
);

CREATE TABLE table_orders
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date      DATE   NOT NULL,
    payment_status  BOOLEAN DEFAULT FALSE,
    order_format_id INT    NOT NULL,
    is_registered   BOOLEAN DEFAULT FALSE,
    client_id       INT    NULL,
    FOREIGN KEY (client_id) REFERENCES table_clients (id),
    FOREIGN KEY (order_format_id) REFERENCES table_order_formats (id)
);

CREATE TABLE table_list_products
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   INT     NOT NULL,
    product_id INT     NOT NULL,
    quantity   NUMERIC NOT NULL CHECK (quantity >= 0.0),
    FOREIGN KEY (order_id) REFERENCES table_orders (id),
    FOREIGN KEY (product_id) REFERENCES table_products (id)
);

CREATE TABLE table_sales
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id  INT    NOT NULL,
    date_sale DATE   NOT NULL,
    seller_id INT    NOT NULL,
    FOREIGN KEY (order_id) REFERENCES table_orders (id),
    FOREIGN KEY (seller_id) REFERENCES table_sellers (id)
);

CREATE OR REPLACE FUNCTION function_archiving()
    RETURNS TRIGGER
AS
$$
BEGIN

    IF (NEW.product_quantity = 0) THEN

        UPDATE table_products
        SET product_stock = TRUE
        WHERE id = NEW.product_id;
        INSERT INTO table_product_archive(product_id)
        VALUES (NEW.product_id);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_archiving
    AFTER INSERT OR UPDATE
    ON table_products
    FOR EACH ROW
    EXECUTE FUNCTION function_archiving();
CREATE VIEW view_orders AS
SELECT table_persons.last_name     AS last_name,
       table_persons.first_name    AS first_name,
       table_orders.id             AS orders_id,
       table_orders.order_date     AS order_date,
       table_orders.payment_status AS payment_status
FROM table_persons
         JOIN table_clients ON table_persons.id = table_clients.person_id
         JOIN table_orders ON table_clients.id = table_orders.client_id
WHERE table_persons.is_deleted = FALSE
ORDER BY table_persons.last_name, table_persons.first_name, table_orders.order_date;